Учебный проект: консольные забавы
htmlacademy-nodejs/144889-buy-and-sell-3 pull request #2
Opened 2021-01-25 21:34 UTC by dimalapeto

2021-01-26 20:53 UTC, dean992008 requested changes
Также нужно обновить свой мастер и смержить его в текущую ветку. Сейчас смержить не могу есть конфликт.

2021-01-26 20:53 UTC, dean992008 commented on src/constants.js
> +  error: 1,
В перечислении ключи должен быть большими буквами. 
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2021-01-26 20:53 UTC, dean992008 commented on src/constants.js
> +module.exports.DEFAULT_COMMAND = `--help`;
Я бы рекомендовал обьявить констенты как локальные а потом экспортировать эти константы в конце модуля.

2021-01-26 20:53 UTC, dean992008 commented on src/service/cli/generate.js
> +const maxOffersGenerate = 1000;
Это должно быть константой.

2021-01-26 20:53 UTC, dean992008 commented on src/service/cli/generate.js
> +  // eslint-disable-next-line consistent-return
Игнор eslint нужно использовать только если по дургому никак. Здесь можно обойтись. 
http://joxi.ru/J2blvyvf0Jppor
P.S. Не первый раз вижу `return console...` подскажи пожалуйста где ты взял этот пример?

2021-01-26 21:20 UTC, dimalapeto commented on src/service/cli/generate.js
> +  // eslint-disable-next-line consistent-return
Согласен, `return console...` не самое хорошее решение. Надо будет написать авторам учебника исправить на странице https://up.htmlacademy.ru/nodejs/3/book/1.10 (https://prnt.sc/xo6wic)

2021-02-02 19:43 UTC, dean992008 commented on src/service/cli/generate.js
> +  // eslint-disable-next-line consistent-return
Сейчас создам ишью автормак курса.

2021-02-02 19:44 UTC, merged