Module2 task2
htmlacademy-nodejs/144889-buy-and-sell-3 pull request #4
Opened 2021-02-14 18:12 UTC by dimalapeto

2021-02-14 20:50 UTC, dean992008 requested changes

2021-02-14 20:50 UTC, dean992008 commented on src/service/cli/generate.js
> +    const sentences = await readFile(FILE_SENTENCES_PATH);
Я порекумендую здесь воспользовать Promise.all для того чтобы выполнить чтение не последовательно, а паралельно. А результат который прийдет в виде массива, деструктуризировать в параметрах `generateOffers`, это какраз позволит сократить количество параметров в generateOffers до 2.

2021-02-14 21:34 UTC, dimalapeto commented on src/service/cli/generate.js
> +    const data = await Promise.all([sentences, titles, categories]);
Правильно понял рекомендацию?

2021-02-16 13:28 UTC, dean992008 requested changes

2021-02-16 13:28 UTC, dean992008 commented on src/service/cli/generate.js
> +    const data = await Promise.all([sentences, titles, categories]);
Не совсем. Должно быть что-то типа такого: 
```
const data = await Promise.all([readFile(FILE_SENTENCES_PATH), readFile(FILE_TITLES_PATH), readFile(FILE_CATEGORIES_PATH)])
```
Так как сделано у тебя всеравно получит 3 результата последовательно, после чего передаст их в промис. 
Также `generateOffers` я бы сделал так: 
```
const generateOffers = (count, [sentences, titles, categories])
```

2021-02-16 13:41 UTC, dean992008 approved these changes

2021-02-16 13:42 UTC, merged